start quarkus BE test 3

diff --git a/.github/workflows/test_workflow.yml b/.github/workflows/test_workflow.yml
--- a/.github/workflows/test_workflow.yml
+++ b/.github/workflows/test_workflow.yml
@@ -61,17 +61,32 @@ jobs:
           POSTGRES_PASSWORD: password
           
   start_backend:
-      runs-on: ubuntu-latest
-      needs: [build_backend, start_database]
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v3
-  
-        - name: List contents of quarkus-app directory
-          run: |
-            ls -R backend/
+    runs-on: ubuntu-latest
+    needs: [build_backend, start_database]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-        - name: Start Quarkus Backend
-          run: |
-            java -jar target/quarkus-app/quarkus-run.jar
-          working-directory: backend
+      - name: List contents of backend directory
+        run: |
+          ls -R backend/
+
+      - name: Find Quarkus JAR file
+        id: find_jar
+        run: echo "::set-output name=jar_path::$(find backend/ -name 'quarkus-run.jar' -print -quit)"
+
+      - name: Check if Quarkus JAR exists
+        id: check_jar
+        run: echo "::set-output name=exists::$(test -n '${{ steps.find_jar.outputs.jar_path }}' && echo true || echo false)"
+
+      - name: Print Quarkus JAR path
+        run: echo "Quarkus JAR path ${{ steps.find_jar.outputs.jar_path }}"
+
+      - name: Start Quarkus Backend
+        run: |
+          if [ "${{ steps.check_jar.outputs.exists }}" == "true" ]; then
+            java -jar "${{ steps.find_jar.outputs.jar_path }}"
+          else
+            echo "Quarkus JAR not found. Skipping backend startup."
+          fi
+        working-directory: backend
